apiVersion: v1
kind: ServiceAccount
metadata:
  name: azsa
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azagentrolebinding
subjects:
- kind: ServiceAccount
  name: azsa
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azagent
  labels:
    app: azagent
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: azagent
  template:
    metadata:
      labels:
        app: azagent
    spec:
      serviceAccountName: azsa
      #securityContext:
      #  fsGroup: 10001
      #  runAsGroup: 10001
      #  runAsNonRoot: true
      #  runAsUser: 10001
      volumes:
      - name: ca-certs
        secret:
          optional: true
          secretName: ca-certs
      #imagePullSecrets:
      #- name: cdtarget-regcred
      containers:
      - name: azagent
        image: ghcr.io/bartvanbenthem/azagent-keda-22:latest
        volumeMounts:
        - name: ca-certs
          mountPath: /usr/local/share/ca-certificates
          readOnly: true
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - update-ca-certificates
        resources:
          limits:
            cpu: 200m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 500Mi
        env:
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azagent-token
                key: AZP_TOKEN
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
          - name: AZP_AGENT_NAME
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_AGENT_NAME
                optional: true
          - name: AGENT_MTU_VALUE
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AGENT_MTU_VALUE
                optional: true
          #- name: HTTP_PROXY
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: HTTP_PROXY
          #      optional: true
          #- name: HTTPS_PROXY
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: HTTPS_PROXY
          #      optional: true
          #- name: http_proxy
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: http_proxy
          #      optional: true
          #- name: https_proxy
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: https_proxy
          #      optional: true
          #- name: FTP_PROXY
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: FTP_PROXY
          #      optional: true
          #- name: PROXY_USER
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: PROXY_USER
          #      optional: true
          #- name: PROXY_PW
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: PROXY_PW
          #      optional: true
          #- name: PROXY_URL
          #  valueFrom:
          #    secretKeyRef:
          #      name: azagent-proxy
          #      key: PROXY_URL
          #      optional: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: azure-pipelines-pool
spec:
  egress:
  - to:
  - ports:
    - port: 443
      protocol: TCP
    - port: 443
      protocol: UDP     
    to:
    - ipBlock:
        cidr: 13.107.6.0/24
    - ipBlock:
        cidr: 13.107.9.0/24
    - ipBlock:
        cidr: 13.107.42.0/24
    - ipBlock:
        cidr: 13.107.43.0/24
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      app: azagent