apiVersion: v1
kind: Endpoints
metadata:
  name: vcenter-proxy # Must be equal to Service name for automatic mapping
  namespace: ingress-nginx
subsets:
- addresses:
  - ip: $CONFIG_VCENTER_IP # IP address of your external service that you would like to proxy requests to
  ports:
  - port: 443
